server:
  listening: "0.0.0.0:8080"
  context-path: "/api"

application:
  processing:
    rf-events:
      merge-period: 5s

data:
  mongo:
    uri: "mongodb://host.docker.internal:27017"
    database: "home-management"

  redis:
    address: "localhost:6379"
    password: ""
    prefix: "home-management"
    db: 0
    ttl:
      rf-event: 1m

broker:
  mqtt:
    uri: "tcp://localhost:1883"
    client-id: "home-management-backend"
    user: "guest"
    password: "guest"
    topics:
      broadcast: "home-management/broadcast"
      devices: "home-management/devices"
      events: "home-management/events"

  rabbitmq:
    uri: "amqp://guest:guest@localhost:5672/"
    queues:
      events: "home-management-events"

log:
  level: INFO
  format: TEXT
  colored: true