package main

import (
	"context"
	"fernandoglatz/home-management/internal/core/common/utils/log"

	"fernandoglatz/home-management/internal/core/common/utils"
	"fernandoglatz/home-management/internal/core/server"
	"fernandoglatz/home-management/internal/infrastructure/config"

	"github.com/joho/godotenv"
)

// @title			home-management
// @version			1.0

// @license.name	Apache 2.0
// @license.url		http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath		/api

// @securityDefinitions.basic	BasicAuth
// @securityDefinitions.apikey	Bearer
// @in 				header
// @name 			X-AUTHORIZATION
// @description     Generated by /authentication

func main() {
	ctx := context.Background()
	godotenv.Load()

	err := config.LoadConfig(ctx)
	if err != nil {
		log.Fatal(ctx).Msg(err.Error())
	}

	err = utils.ConnectToMongoDB(ctx)
	if err != nil {
		log.Fatal(ctx).Msg(err.Error())
	}

	err = server.Setup(ctx)
	if err != nil {
		log.Fatal(ctx).Msg(err.Error())
	}

}
