server:
  listening: "0.0.0.0:8080"
  allow-origin: "http://localhost:3000"

database:
  uri: "mongodb://localhost:27017"
  name: "home-management"

mosquitto:
  uri: "tcp://localhost:1883"
  topic: "esp32/to-server"
